### ISSUE TITLE
Feature request: Filter by author

### ISSUE THREAD

**Issue by SubJunk** [eps1lon/actions-label-merge-conflict#113]
Hi, thank you for this Action, it's really useful for me! I'm using it to help automate Dependabot changelogs.
It would be great if I could make it only look at PRs opened by certain authors (in my case, Dependabot). Is that possible?

This is my use case, basically this Action just needs to leave a comment on Dependabot pull requests to tell it to recreate the PR: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/cd219026f348853c4bcb1e971160af54c352a90a/.github/workflows/pull-request-conflict.yaml and that works along with this step https://github.com/UniversalMediaServer/UniversalMediaServer/blob/cd219026f348853c4bcb1e971160af54c352a90a/.github/workflows/ci.yaml#L258-L275 which updates the changelog in the Dependabot PRs

**Comment by eps1lon** [comment]
Can't you do this on your own by skipping the action via `if`? E.g. 

```yml
steps:
  - name: check if prs are dirty
    if: ${{ github.event.pull_request.user.login == 'dependabot' }
    uses: eps1lon/actions-label-merge-conflict@v3
```
