### ISSUE TITLE
Changes requested

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [eps1lon/actions-label-merge-conflict#83]
Hi @eps1lon,

First of all i want to thankyou for this amazing workflow.
I know this is a very very very low priory and not even in the scope of this workflow but i had to ask.

Is it possible for u to create this workflow with changes requested?
It would be almost the same as the current workflow.

The workflow only needs to know if there are requested changes on a PR -> add label -> on new commits -> remove label 

If we look at https://github.com/eps1lon/actions-label-merge-conflict#example-usage
U can remove `commentOnDirty` and `commentOnClean` because that is not necessary

Now u have 

```
on:
  push:
  pull_request_target:
    types: [synchronize]
```

Needs to be

```
on:
  pull_request_review:
    types: [submitted]
  pull_request_target:
    types: [synchronize]
```
