### ISSUE TITLE
Misconfiguration or does this action waste a lot of CI time (and money)?

### ISSUE THREAD

**Issue by alexciesielski** [eps1lon/actions-label-merge-conflict#84]
Hey,

first of all this is a really great action so I'm definitely grateful.

One thing I noticed though is that in our repository, where we currently have about 20 open PRs this action runs on every PR and it does so for about 10 minutes.

That is a lot of CI time wasted just for adding a label, so I'm wondering if I misunderstood or misconfigured the action maybe?
Or is this just the nature of it? I definitely don't mean to complain, just trying to understand.

```
- name: Check if PR branch has conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          dirtyLabel: 'pr: conflicted'
          removeOnDirtyLabel: 'pr: conflicted'
```
